efault: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: incident_slack_bot_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= Rails.application.credentials.incident_slack[:postgres_password] %>

test:
  <<: *default
  database: incident_slack_bot_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= Rails.application.credentials.incident_slack[:postgres_password] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= Rails.application.credentials.incident_slack[:postgres_password] %>
